import {SurveyStep} from "@/constants/interface";

export enum SurveyStatus {
    LifeStyleStep = "LifeStyleStep",
    SportStyleStep = "SportStyleStep",
    HealthStyleStep = "HealthStyleStep",
    NutritionStyleStep = "NutritionStyleStep",
    AgeStep = "AgeStep",
    WeightStep = "WeightStep",
    FrontViewPhotoStep = "FrontViewPhotoStep",
    SideViewPhotoStep = "SideViewPhotoStep",
    FrontViewWithRaisedLegPhotoStep = "FrontViewWithRaisedLegPhotoStep",
    SideViewWithRaisedLegPhotoStep = "SideViewWithRaisedLegPhotoStep",
    WaitingForResults = "WaitingForResults",
    FirstReviewDone = "FirstReviewDone"
}

export const surveySteps: SurveyStep[] = [
    {
        stepNumber: 1,
        type: 'multianswer',
        slug: 'lifestyle',
        status: SurveyStatus.LifeStyleStep,
        field: 'lifestyle',
        nextStatus: SurveyStatus.SportStyleStep,
        nextSlug: "sportstyle",
        question: 'What is your lifestyle ?',
        description: 'Select one or more options'
    },
    {
        stepNumber: 2,
        type: 'multianswer',
        slug: 'sportstyle',
        status: SurveyStatus.SportStyleStep,
        field: 'sportstyle',
        nextStatus: SurveyStatus.HealthStyleStep,
        nextSlug: "healthstyle",
        question: 'What is your sport style ?',
        description: 'Select one or more options'
    },
    {
        stepNumber: 3,
        type: 'multianswer',
        slug: 'healthstyle',
        status: SurveyStatus.HealthStyleStep,
        field: 'healthstyle',
        nextStatus: SurveyStatus.NutritionStyleStep,
        nextSlug: "nutritionstyle",
        question: 'What is your health ?',
        description: 'Select one or more options'
    },
    {
        stepNumber: 4,
        type: 'multianswer',
        slug: 'nutritionstyle',
        status: SurveyStatus.NutritionStyleStep,
        field: 'nutritionstyle',
        nextStatus: SurveyStatus.AgeStep,
        nextSlug: "age",
        question: 'What is your nutrition ?',
        description: 'Select one or more options'
    },
    {
        stepNumber: 5,
        type: 'numberinput',
        slug: 'age',
        status: SurveyStatus.AgeStep,
        field: 'age',
        nextStatus: SurveyStatus.WeightStep,
        nextSlug: "weight",
        title: "Age",
        placeholder: "Your age in years",
        question: 'How old are you ?',
    },
    {
        stepNumber: 6,
        type: 'numberinput',
        slug: 'weight',
        status: SurveyStatus.WeightStep,
        field: 'weight',
        nextStatus: SurveyStatus.FrontViewPhotoStep,
        nextSlug: "front-view",
        title: "Weight",
        placeholder: "Your weight in kg",
        question: 'How much do you weight ?',
    },
    {
        stepNumber: 7,
        type: 'photoupload',
        slug: "front-view",
        status: SurveyStatus.FrontViewPhotoStep,
        field: 'photos',
        nextStatus: SurveyStatus.SideViewPhotoStep,
        nextSlug: "side-view",
        question: "Front View Photos",
        description: "Upload 2 photos like on a pictures below",
        samplePhoto1: "https://cloud.appwrite.io/v1/storage/buckets/66c331f000314ec68775/files/66e2af30002b4045effa/view?project=66c32ed800357b5e7314&project=66c32ed800357b5e7314",
        samplePhoto2: "https://cloud.appwrite.io/v1/storage/buckets/66c331f000314ec68775/files/66e2af30002b4045effa/view?project=66c32ed800357b5e7314&project=66c32ed800357b5e7314",
    },
    {
        stepNumber: 8,
        type: 'photoupload',
        slug: "side-view",
        status: SurveyStatus.SideViewPhotoStep,
        field: 'photos',
        nextStatus: SurveyStatus.FrontViewWithRaisedLegPhotoStep,
        nextSlug: "front-view-raised-leg",
        question: "Side View Photos",
        description: "Upload 2 photos like on a pictures below",
        samplePhoto1: "https://cloud.appwrite.io/v1/storage/buckets/66c331f000314ec68775/files/66e2af30002b4045effa/view?project=66c32ed800357b5e7314&project=66c32ed800357b5e7314",
        samplePhoto2: "https://cloud.appwrite.io/v1/storage/buckets/66c331f000314ec68775/files/66e2af30002b4045effa/view?project=66c32ed800357b5e7314&project=66c32ed800357b5e7314",
    },
    {
        stepNumber: 9,
        type: 'photoupload',
        slug: "front-view-raised-leg",
        status: SurveyStatus.FrontViewWithRaisedLegPhotoStep,
        field: 'photos',
        nextStatus: SurveyStatus.SideViewWithRaisedLegPhotoStep,
        nextSlug: "side-view-raised-leg",
        question: "Front View Photos With Raised Leg",
        description: "Upload 2 photos like on a pictures below",
        samplePhoto1: "https://cloud.appwrite.io/v1/storage/buckets/66c331f000314ec68775/files/66e2af30002b4045effa/view?project=66c32ed800357b5e7314&project=66c32ed800357b5e7314",
        samplePhoto2: "https://cloud.appwrite.io/v1/storage/buckets/66c331f000314ec68775/files/66e2af30002b4045effa/view?project=66c32ed800357b5e7314&project=66c32ed800357b5e7314",
    },
    {
        stepNumber: 10,
        type: 'photoupload',
        slug: "side-view-raised-leg",
        status: SurveyStatus.SideViewWithRaisedLegPhotoStep,
        field: 'photos',
        nextStatus: SurveyStatus.WaitingForResults,
        nextSlug: null,
        question: "Side View Photos With Raised Leg",
        description: "Upload 2 photos like on a pictures below",
        samplePhoto1: "https://cloud.appwrite.io/v1/storage/buckets/66c331f000314ec68775/files/66e2af30002b4045effa/view?project=66c32ed800357b5e7314&project=66c32ed800357b5e7314",
        samplePhoto2: "https://cloud.appwrite.io/v1/storage/buckets/66c331f000314ec68775/files/66e2af30002b4045effa/view?project=66c32ed800357b5e7314&project=66c32ed800357b5e7314",
    }
]