### Verify Firebase ID Token
POST http://localhost:8080/api/v1/auth/verify-token
Content-Type: application/json
Accept: application/json

{
  "idToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjFhYWMyNzEwOTkwNDljMGRmYzA1OGUwNjEyZjA4ZDA2YzMwYTA0MTUiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiQWRtaW4iLCJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZml0LXJldmlldy03M2FlMiIsImF1ZCI6ImZpdC1yZXZpZXctNzNhZTIiLCJhdXRoX3RpbWUiOjE3MzQ1NTk0NTAsInVzZXJfaWQiOiJib1BWejRRSFkwYkpCSWkxUGhpSmZDaEJnTEkyIiwic3ViIjoiYm9QVno0UUhZMGJKQklpMVBoaUpmQ2hCZ0xJMiIsImlhdCI6MTczNDU1OTQ1MCwiZXhwIjoxNzM0NTYzMDUwLCJlbWFpbCI6InZpbnRvcmV6aW5AZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInZpbnRvcmV6aW5AZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.zGpBewPP1Vw4cR3XoNp2M2mE2x_8PVi57x-BKNRhMvFcAFRHNgKYxtfd4fKqyX0Rm1-cB6UEkCug5ZNgWenIL-yiWFE5B9CAyXkqTL-LCnsLFAmfOjWZSfAHD5T-aQFXvH0eR-UnIy3lbeVuxu4dP9SkcyR9hqJfmlWpvTeB2i1ih4mvzE6By47HvOuDd90SgOd8iAYil8cX8b3Wtm6haYffXu5w8i1CT_bZr_nMIQ8jZzhtePTKEnMuKUlst6AXxRxOaMp3NtIlMhPB4Ixf0Pk1wJhg-_5gG5iA3qso70EpGrCewjni9M_z5Eq9-nzgNSEFngI4drR0kskkpn3X-g"
}
