### Get Last Review By UserId
GET http://localhost:8080/api/v1/review/1
Accept: application/json

### Get Last ReviewStatus By UserId
GET http://localhost:8080/api/v1/review/status/1
Accept: application/json

### Post Create New ReviewStatus Record
POST http://localhost:8080/api/v1/review/status
Content-Type: application/json

{
  "userId": "1",
  "status": "PaymentScreen"
}
