POST https://cloud.appwrite.io/v1/databases/66c3312f002e44e586ce/collections/66c76bdf0003e4f2041f/documents
Content-Type: application/json
X-Appwrite-Project: 66c32ed800357b5e7314
X-Appwrite-Key: 27fcf2ca888ed890e1dc68d5cf5f450d5ada0843c1ba560e450f37335c4b39de2b74ad7b44ede4a609e12495c90dc680903ebf3784b91f8943ada57b91996efa10cea61413f69fb3419633adbb17c70ca302103279a7b42e053beefdc693216f131cef6b910f24fb06542b8b09936f0d10997fd3f7f6f69f7cad9398e77366ad

{
  "databaseId": "66c3312f002e44e586ce",
  "collectionId": "66c76bdf0003e4f2041f",
  "documentId": "exercise-070",
  "data": {
    "title": "Big Toe Base Activation (No Band)",
    "russianTitle": "Активация основания большого пальца (без резинки)",
    "thumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise-big.png",
    "youtubeVideoId": "gJh03s2HNeo",
    "level": "Beginner",
    "time": 5,
    "region": "Feet",
    "complexity": "Easy",
    "instructions": [
      "Test_Exr","Test_Exr","Test_Exr"
    ],
    "shortThumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise.png",
    "exerciseId": 70,
    "description": "Test_Exr",
    "subcategory": "drill"
  }
}
###

POST https://cloud.appwrite.io/v1/databases/66c3312f002e44e586ce/collections/66c76bdf0003e4f2041f/documents
Content-Type: application/json
X-Appwrite-Project: 66c32ed800357b5e7314
X-Appwrite-Key: 27fcf2ca888ed890e1dc68d5cf5f450d5ada0843c1ba560e450f37335c4b39de2b74ad7b44ede4a609e12495c90dc680903ebf3784b91f8943ada57b91996efa10cea61413f69fb3419633adbb17c70ca302103279a7b42e053beefdc693216f131cef6b910f24fb06542b8b09936f0d10997fd3f7f6f69f7cad9398e77366ad

{
  "databaseId": "66c3312f002e44e586ce",
  "collectionId": "66c76bdf0003e4f2041f",
  "documentId": "exercise-071",
  "data": {
    "title": "Fingers to Fist and Reverse",
    "russianTitle": "Пальцы в кулак и наоборот",
    "thumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise-big.png",
    "youtubeVideoId": "gJh03s2HNeo",
    "level": "Beginner",
    "time": 5,
    "region": "Feet",
    "complexity": "Easy",
    "instructions": [
      "Test_Exr","Test_Exr","Test_Exr"
    ],
    "shortThumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise.png",
    "exerciseId": 71,
    "description": "Test_Exr",
    "subcategory": "drill"
  }
}
###

POST https://cloud.appwrite.io/v1/databases/66c3312f002e44e586ce/collections/66c76bdf0003e4f2041f/documents
Content-Type: application/json
X-Appwrite-Project: 66c32ed800357b5e7314
X-Appwrite-Key: 27fcf2ca888ed890e1dc68d5cf5f450d5ada0843c1ba560e450f37335c4b39de2b74ad7b44ede4a609e12495c90dc680903ebf3784b91f8943ada57b91996efa10cea61413f69fb3419633adbb17c70ca302103279a7b42e053beefdc693216f131cef6b910f24fb06542b8b09936f0d10997fd3f7f6f69f7cad9398e77366ad

{
  "databaseId": "66c3312f002e44e586ce",
  "collectionId": "66c76bdf0003e4f2041f",
  "documentId": "exercise-072",
  "data": {
    "title": "Arch Activation",
    "russianTitle": "Активация арки стопы",
    "thumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise-big.png",
    "youtubeVideoId": "gJh03s2HNeo",
    "level": "Beginner",
    "time": 5,
    "region": "Feet",
    "complexity": "Easy",
    "instructions": [
      "Test_Exr","Test_Exr","Test_Exr"
    ],
    "shortThumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise.png",
    "exerciseId": 72,
    "description": "Test_Exr",
    "subcategory": "drill"
  }
}
###

POST https://cloud.appwrite.io/v1/databases/66c3312f002e44e586ce/collections/66c76bdf0003e4f2041f/documents
Content-Type: application/json
X-Appwrite-Project: 66c32ed800357b5e7314
X-Appwrite-Key: 27fcf2ca888ed890e1dc68d5cf5f450d5ada0843c1ba560e450f37335c4b39de2b74ad7b44ede4a609e12495c90dc680903ebf3784b91f8943ada57b91996efa10cea61413f69fb3419633adbb17c70ca302103279a7b42e053beefdc693216f131cef6b910f24fb06542b8b09936f0d10997fd3f7f6f69f7cad9398e77366ad

{
  "databaseId": "66c3312f002e44e586ce",
  "collectionId": "66c76bdf0003e4f2041f",
  "documentId": "exercise-073",
  "data": {
    "title": "Big Toe Base Activation with Band",
    "russianTitle": "Активация основания большого пальца с резинкой",
    "thumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise-big.png",
    "youtubeVideoId": "gJh03s2HNeo",
    "level": "Beginner",
    "time": 5,
    "region": "Feet",
    "complexity": "Easy",
    "instructions": [
      "Test_Exr","Test_Exr","Test_Exr"
    ],
    "shortThumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise.png",
    "exerciseId": 73,
    "description": "Test_Exr",
    "subcategory": "drill"
  }
}
###

POST https://cloud.appwrite.io/v1/databases/66c3312f002e44e586ce/collections/66c76bdf0003e4f2041f/documents
Content-Type: application/json
X-Appwrite-Project: 66c32ed800357b5e7314
X-Appwrite-Key: 27fcf2ca888ed890e1dc68d5cf5f450d5ada0843c1ba560e450f37335c4b39de2b74ad7b44ede4a609e12495c90dc680903ebf3784b91f8943ada57b91996efa10cea61413f69fb3419633adbb17c70ca302103279a7b42e053beefdc693216f131cef6b910f24fb06542b8b09936f0d10997fd3f7f6f69f7cad9398e77366ad

{
  "databaseId": "66c3312f002e44e586ce",
  "collectionId": "66c76bdf0003e4f2041f",
  "documentId": "exercise-074",
  "data": {
    "title": "Peroneal Tract Activation",
    "russianTitle": "Активация малоберцовый тракт",
    "thumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise-big.png",
    "youtubeVideoId": "gJh03s2HNeo",
    "level": "Beginner",
    "time": 5,
    "region": "Feet",
    "complexity": "Easy",
    "instructions": [
      "Test_Exr","Test_Exr","Test_Exr"
    ],
    "shortThumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise.png",
    "exerciseId": 74,
    "description": "Test_Exr",
    "subcategory": "drill"
  }
}
###

POST https://cloud.appwrite.io/v1/databases/66c3312f002e44e586ce/collections/66c76bdf0003e4f2041f/documents
Content-Type: application/json
X-Appwrite-Project: 66c32ed800357b5e7314
X-Appwrite-Key: 27fcf2ca888ed890e1dc68d5cf5f450d5ada0843c1ba560e450f37335c4b39de2b74ad7b44ede4a609e12495c90dc680903ebf3784b91f8943ada57b91996efa10cea61413f69fb3419633adbb17c70ca302103279a7b42e053beefdc693216f131cef6b910f24fb06542b8b09936f0d10997fd3f7f6f69f7cad9398e77366ad

{
  "databaseId": "66c3312f002e44e586ce",
  "collectionId": "66c76bdf0003e4f2041f",
  "documentId": "exercise-075",
  "data": {
    "title": "Tibial Tract Activation",
    "russianTitle": "Активация большеберцовый тракт",
    "thumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise-big.png",
    "youtubeVideoId": "gJh03s2HNeo",
    "level": "Beginner",
    "time": 5,
    "region": "Feet",
    "complexity": "Easy",
    "instructions": [
      "Test_Exr","Test_Exr","Test_Exr"
    ],
    "shortThumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise.png",
    "exerciseId": 75,
    "description": "Test_Exr",
    "subcategory": "drill"
  }
}
###

POST https://cloud.appwrite.io/v1/databases/66c3312f002e44e586ce/collections/66c76bdf0003e4f2041f/documents
Content-Type: application/json
X-Appwrite-Project: 66c32ed800357b5e7314
X-Appwrite-Key: 27fcf2ca888ed890e1dc68d5cf5f450d5ada0843c1ba560e450f37335c4b39de2b74ad7b44ede4a609e12495c90dc680903ebf3784b91f8943ada57b91996efa10cea61413f69fb3419633adbb17c70ca302103279a7b42e053beefdc693216f131cef6b910f24fb06542b8b09936f0d10997fd3f7f6f69f7cad9398e77366ad

{
  "databaseId": "66c3312f002e44e586ce",
  "collectionId": "66c76bdf0003e4f2041f",
  "documentId": "exercise-076",
  "data": {
    "title": "Calf Activation",
    "russianTitle": "Активация икроножные",
    "thumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise-big.png",
    "youtubeVideoId": "gJh03s2HNeo",
    "level": "Beginner",
    "time": 5,
    "region": "Feet",
    "complexity": "Easy",
    "instructions": [
      "Test_Exr","Test_Exr","Test_Exr"
    ],
    "shortThumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise.png",
    "exerciseId": 76,
    "description": "Test_Exr",
    "subcategory": "drill"
  }
}
###

