# === Стадия 1: Сборка проекта ===
FROM node:20 AS builder

WORKDIR /app

COPY miniapp/package*.json ./
RUN npm install --force

COPY miniapp/ ./
RUN npm run build

# === Стадия 2: Запуск приложения ===
FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app/package*.json /app/
COPY --from=builder /app/node_modules /app/node_modules
COPY --from=builder /app/.next /app/.next
COPY --from=builder /app/public /app/public

ENV PORT=3001
EXPOSE 3001

CMD ["npm", "run", "start"]
