POST https://cloud.appwrite.io/v1/databases/66c3312f002e44e586ce/collections/66c76bdf0003e4f2041f/documents
Content-Type: application/json
X-Appwrite-Project: 66c32ed800357b5e7314
X-Appwrite-Key: 27fcf2ca888ed890e1dc68d5cf5f450d5ada0843c1ba560e450f37335c4b39de2b74ad7b44ede4a609e12495c90dc680903ebf3784b91f8943ada57b91996efa10cea61413f69fb3419633adbb17c70ca302103279a7b42e053beefdc693216f131cef6b910f24fb06542b8b09936f0d10997fd3f7f6f69f7cad9398e77366ad

{
  "databaseId": "66c3312f002e44e586ce",
  "collectionId": "66c76bdf0003e4f2041f",
  "documentId": "exercise-065",
  "data": {
    "title": "Ankle Flexion with Resistance Band",
    "russianTitle": "Сгибание галеностопного сустава с резинкой",
    "thumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise-big.png",
    "youtubeVideoId": "gJh03s2HNeo",
    "level": "Beginner",
    "time": 5,
    "region": "Feet",
    "complexity": "Easy",
    "instructions": [
      "Test_Exr","Test_Exr","Test_Exr"
    ],
    "shortThumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise.png",
    "exerciseId": 65,
    "description": "Test_Exr",
    "subcategory": "mobility"
  }
}
###

POST https://cloud.appwrite.io/v1/databases/66c3312f002e44e586ce/collections/66c76bdf0003e4f2041f/documents
Content-Type: application/json
X-Appwrite-Project: 66c32ed800357b5e7314
X-Appwrite-Key: 27fcf2ca888ed890e1dc68d5cf5f450d5ada0843c1ba560e450f37335c4b39de2b74ad7b44ede4a609e12495c90dc680903ebf3784b91f8943ada57b91996efa10cea61413f69fb3419633adbb17c70ca302103279a7b42e053beefdc693216f131cef6b910f24fb06542b8b09936f0d10997fd3f7f6f69f7cad9398e77366ad

{
  "databaseId": "66c3312f002e44e586ce",
  "collectionId": "66c76bdf0003e4f2041f",
  "documentId": "exercise-066",
  "data": {
    "title": "Toe Abduction",
    "russianTitle": "Отведение пальцев",
    "thumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise-big.png",
    "youtubeVideoId": "gJh03s2HNeo",
    "level": "Beginner",
    "time": 5,
    "region": "Feet",
    "complexity": "Easy",
    "instructions": [
      "Test_Exr","Test_Exr","Test_Exr"
    ],
    "shortThumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise.png",
    "exerciseId": 66,
    "description": "Test_Exr",
    "subcategory": "mobility"
  }
}
###

POST https://cloud.appwrite.io/v1/databases/66c3312f002e44e586ce/collections/66c76bdf0003e4f2041f/documents
Content-Type: application/json
X-Appwrite-Project: 66c32ed800357b5e7314
X-Appwrite-Key: 27fcf2ca888ed890e1dc68d5cf5f450d5ada0843c1ba560e450f37335c4b39de2b74ad7b44ede4a609e12495c90dc680903ebf3784b91f8943ada57b91996efa10cea61413f69fb3419633adbb17c70ca302103279a7b42e053beefdc693216f131cef6b910f24fb06542b8b09936f0d10997fd3f7f6f69f7cad9398e77366ad

{
  "databaseId": "66c3312f002e44e586ce",
  "collectionId": "66c76bdf0003e4f2041f",
  "documentId": "exercise-067",
  "data": {
    "title": "Big Toe Lift for Varus",
    "russianTitle": "Подъем большого пальца если варус",
    "thumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise-big.png",
    "youtubeVideoId": "gJh03s2HNeo",
    "level": "Beginner",
    "time": 5,
    "region": "Feet",
    "complexity": "Easy",
    "instructions": [
      "Test_Exr","Test_Exr","Test_Exr"
    ],
    "shortThumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise.png",
    "exerciseId": 67,
    "description": "Test_Exr",
    "subcategory": "mobility"
  }
}
###

POST https://cloud.appwrite.io/v1/databases/66c3312f002e44e586ce/collections/66c76bdf0003e4f2041f/documents
Content-Type: application/json
X-Appwrite-Project: 66c32ed800357b5e7314
X-Appwrite-Key: 27fcf2ca888ed890e1dc68d5cf5f450d5ada0843c1ba560e450f37335c4b39de2b74ad7b44ede4a609e12495c90dc680903ebf3784b91f8943ada57b91996efa10cea61413f69fb3419633adbb17c70ca302103279a7b42e053beefdc693216f131cef6b910f24fb06542b8b09936f0d10997fd3f7f6f69f7cad9398e77366ad

{
  "databaseId": "66c3312f002e44e586ce",
  "collectionId": "66c76bdf0003e4f2041f",
  "documentId": "exercise-068",
  "data": {
    "title": "Toe Lifts",
    "russianTitle": "Подъем пальцев",
    "thumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise-big.png",
    "youtubeVideoId": "gJh03s2HNeo",
    "level": "Beginner",
    "time": 5,
    "region": "Feet",
    "complexity": "Easy",
    "instructions": [
      "Test_Exr","Test_Exr","Test_Exr"
    ],
    "shortThumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise.png",
    "exerciseId": 68,
    "description": "Test_Exr",
    "subcategory": "mobility"
  }
}
###

POST https://cloud.appwrite.io/v1/databases/66c3312f002e44e586ce/collections/66c76bdf0003e4f2041f/documents
Content-Type: application/json
X-Appwrite-Project: 66c32ed800357b5e7314
X-Appwrite-Key: 27fcf2ca888ed890e1dc68d5cf5f450d5ada0843c1ba560e450f37335c4b39de2b74ad7b44ede4a609e12495c90dc680903ebf3784b91f8943ada57b91996efa10cea61413f69fb3419633adbb17c70ca302103279a7b42e053beefdc693216f131cef6b910f24fb06542b8b09936f0d10997fd3f7f6f69f7cad9398e77366ad

{
  "databaseId": "66c3312f002e44e586ce",
  "collectionId": "66c76bdf0003e4f2041f",
  "documentId": "exercise-069",
  "data": {
    "title": "Rotation + Wave",
    "russianTitle": "Вращение + Волна",
    "thumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise-big.png",
    "youtubeVideoId": "gJh03s2HNeo",
    "level": "Beginner",
    "time": 5,
    "region": "Feet",
    "complexity": "Easy",
    "instructions": [
      "Test_Exr","Test_Exr","Test_Exr"
    ],
    "shortThumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise.png",
    "exerciseId": 69,
    "description": "Test_Exr",
    "subcategory": "mobility"
  }
}
