spring:
  datasource:
    username: admin
    password: fitreview010824
    url: jdbc:postgresql://34.32.80.79:5432/fitreviewdb
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true
    open-in-view: false

gcp:
  storage:
    basic-url: https://storage.googleapis.com/
    bucket-name: fit_review
    client-email: fr-storage-service-account@fit-review-444116.iam.gserviceaccount.com
    private-key-id: ${GOOGLE_STORAGE_PRIVATE_KEY_ID}
    private-key: ${GOOGLE_STORAGE_PRIVATE_KEY}
    client-id: 105107947195209788558
    project-id: fit-review-444116

security:
  allowed-paths:
    - /api/v1/auth
    - /api/v1/storage/public
    - /api/v1/training/public
    - /api/v1/survey/public