spring:
  datasource:
    username: admin
    password: fitreview010824
    url: jdbc:postgresql://34.32.80.79:5432/fitreviewdb
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true
    open-in-view: false