POST https://cloud.appwrite.io/v1/databases/66c3312f002e44e586ce/collections/66c76bdf0003e4f2041f/documents
Content-Type: application/json
X-Appwrite-Project: 66c32ed800357b5e7314
X-Appwrite-Key: 27fcf2ca888ed890e1dc68d5cf5f450d5ada0843c1ba560e450f37335c4b39de2b74ad7b44ede4a609e12495c90dc680903ebf3784b91f8943ada57b91996efa10cea61413f69fb3419633adbb17c70ca302103279a7b42e053beefdc693216f131cef6b910f24fb06542b8b09936f0d10997fd3f7f6f69f7cad9398e77366ad

{
  "databaseId": "66c3312f002e44e586ce",
  "collectionId": "66c76bdf0003e4f2041f",
  "documentId": "exercise-036",
  "data": {
    "title": "Chest Rotation with Block",
    "russianTitle": "Ротация грудного отдела с кубиком",
    "thumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise-big.png",
    "youtubeVideoId": "gJh03s2HNeo",
    "level": "Beginner",
    "time": 5,
    "region": "Core",
    "complexity": "Easy",
    "instructions": [
      "Test_Exr","Test_Exr","Test_Exr"
    ],
    "shortThumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise.png",
    "exerciseId": 36,
    "description": "Test_Exr",
    "subcategory": "mobility"
  }
}
###

POST https://cloud.appwrite.io/v1/databases/66c3312f002e44e586ce/collections/66c76bdf0003e4f2041f/documents
Content-Type: application/json
X-Appwrite-Project: 66c32ed800357b5e7314
X-Appwrite-Key: 27fcf2ca888ed890e1dc68d5cf5f450d5ada0843c1ba560e450f37335c4b39de2b74ad7b44ede4a609e12495c90dc680903ebf3784b91f8943ada57b91996efa10cea61413f69fb3419633adbb17c70ca302103279a7b42e053beefdc693216f131cef6b910f24fb06542b8b09936f0d10997fd3f7f6f69f7cad9398e77366ad

{
  "databaseId": "66c3312f002e44e586ce",
  "collectionId": "66c76bdf0003e4f2041f",
  "documentId": "exercise-037",
  "data": {
    "title": "Side-Lying Rotation with Block",
    "russianTitle": "Ротация лежа на боку с кубиком",
    "thumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise-big.png",
    "youtubeVideoId": "gJh03s2HNeo",
    "level": "Beginner",
    "time": 5,
    "region": "Core",
    "complexity": "Easy",
    "instructions": [
      "Test_Exr","Test_Exr","Test_Exr"
    ],
    "shortThumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise.png",
    "exerciseId": 37,
    "description": "Test_Exr",
    "subcategory": "mobility"
  }
}
###

POST https://cloud.appwrite.io/v1/databases/66c3312f002e44e586ce/collections/66c76bdf0003e4f2041f/documents
Content-Type: application/json
X-Appwrite-Project: 66c32ed800357b5e7314
X-Appwrite-Key: 27fcf2ca888ed890e1dc68d5cf5f450d5ada0843c1ba560e450f37335c4b39de2b74ad7b44ede4a609e12495c90dc680903ebf3784b91f8943ada57b91996efa10cea61413f69fb3419633adbb17c70ca302103279a7b42e053beefdc693216f131cef6b910f24fb06542b8b09936f0d10997fd3f7f6f69f7cad9398e77366ad

{
  "databaseId": "66c3312f002e44e586ce",
  "collectionId": "66c76bdf0003e4f2041f",
  "documentId": "exercise-038",
  "data": {
    "title": "Wall Standing Flexion",
    "russianTitle": "Сгибание у стенки стоя",
    "thumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise-big.png",
    "youtubeVideoId": "gJh03s2HNeo",
    "level": "Beginner",
    "time": 5,
    "region": "Core",
    "complexity": "Easy",
    "instructions": [
      "Test_Exr","Test_Exr","Test_Exr"
    ],
    "shortThumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise.png",
    "exerciseId": 38,
    "description": "Test_Exr",
    "subcategory": "mobility"
  }
}
###

POST https://cloud.appwrite.io/v1/databases/66c3312f002e44e586ce/collections/66c76bdf0003e4f2041f/documents
Content-Type: application/json
X-Appwrite-Project: 66c32ed800357b5e7314
X-Appwrite-Key: 27fcf2ca888ed890e1dc68d5cf5f450d5ada0843c1ba560e450f37335c4b39de2b74ad7b44ede4a609e12495c90dc680903ebf3784b91f8943ada57b91996efa10cea61413f69fb3419633adbb17c70ca302103279a7b42e053beefdc693216f131cef6b910f24fb06542b8b09936f0d10997fd3f7f6f69f7cad9398e77366ad

{
  "databaseId": "66c3312f002e44e586ce",
  "collectionId": "66c76bdf0003e4f2041f",
  "documentId": "exercise-039",
  "data": {
    "title": "Lower Back Unloading on All Fours",
    "russianTitle": "Разгрузка поясничного региона на четвереньках",
    "thumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise-big.png",
    "youtubeVideoId": "gJh03s2HNeo",
    "level": "Beginner",
    "time": 5,
    "region": "Core",
    "complexity": "Easy",
    "instructions": [
      "Test_Exr","Test_Exr","Test_Exr"
    ],
    "shortThumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise.png",
    "exerciseId": 39,
    "description": "Test_Exr",
    "subcategory": "mobility"
  }
}
###

POST https://cloud.appwrite.io/v1/databases/66c3312f002e44e586ce/collections/66c76bdf0003e4f2041f/documents
Content-Type: application/json
X-Appwrite-Project: 66c32ed800357b5e7314
X-Appwrite-Key: 27fcf2ca888ed890e1dc68d5cf5f450d5ada0843c1ba560e450f37335c4b39de2b74ad7b44ede4a609e12495c90dc680903ebf3784b91f8943ada57b91996efa10cea61413f69fb3419633adbb17c70ca302103279a7b42e053beefdc693216f131cef6b910f24fb06542b8b09936f0d10997fd3f7f6f69f7cad9398e77366ad

{
  "databaseId": "66c3312f002e44e586ce",
  "collectionId": "66c76bdf0003e4f2041f",
  "documentId": "exercise-040",
  "data": {
    "title": "Seated 90/90 Side Bend",
    "russianTitle": "Боковой наклон сидя 90/90",
    "thumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise-big.png",
    "youtubeVideoId": "gJh03s2HNeo",
    "level": "Beginner",
    "time": 5,
    "region": "Core",
    "complexity": "Easy",
    "instructions": [
      "Test_Exr","Test_Exr","Test_Exr"
    ],
    "shortThumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise.png",
    "exerciseId": 40,
    "description": "Test_Exr",
    "subcategory": "mobility"
  }
}
###

POST https://cloud.appwrite.io/v1/databases/66c3312f002e44e586ce/collections/66c76bdf0003e4f2041f/documents
Content-Type: application/json
X-Appwrite-Project: 66c32ed800357b5e7314
X-Appwrite-Key: 27fcf2ca888ed890e1dc68d5cf5f450d5ada0843c1ba560e450f37335c4b39de2b74ad7b44ede4a609e12495c90dc680903ebf3784b91f8943ada57b91996efa10cea61413f69fb3419633adbb17c70ca302103279a7b42e053beefdc693216f131cef6b910f24fb06542b8b09936f0d10997fd3f7f6f69f7cad9398e77366ad

{
  "databaseId": "66c3312f002e44e586ce",
  "collectionId": "66c76bdf0003e4f2041f",
  "documentId": "exercise-041",
  "data": {
    "title": "Standing Rib Expansion",
    "russianTitle": "Раскрытие ребер стоя",
    "thumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise-big.png",
    "youtubeVideoId": "gJh03s2HNeo",
    "level": "Beginner",
    "time": 5,
    "region": "Core",
    "complexity": "Easy",
    "instructions": [
      "Test_Exr","Test_Exr","Test_Exr"
    ],
    "shortThumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise.png",
    "exerciseId": 41,
    "description": "Test_Exr",
    "subcategory": "mobility"
  }
}
###

