POST https://cloud.appwrite.io/v1/databases/66c3312f002e44e586ce/collections/66c76bdf0003e4f2041f/documents
Content-Type: application/json
X-Appwrite-Project: 66c32ed800357b5e7314
X-Appwrite-Key: 27fcf2ca888ed890e1dc68d5cf5f450d5ada0843c1ba560e450f37335c4b39de2b74ad7b44ede4a609e12495c90dc680903ebf3784b91f8943ada57b91996efa10cea61413f69fb3419633adbb17c70ca302103279a7b42e053beefdc693216f131cef6b910f24fb06542b8b09936f0d10997fd3f7f6f69f7cad9398e77366ad

{
  "databaseId": "66c3312f002e44e586ce",
  "collectionId": "66c76bdf0003e4f2041f",
  "documentId": "exercise-042",
  "data": {
    "title": "Belly Breathing",
    "russianTitle": "Дыхание животом",
    "thumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise-big.png",
    "youtubeVideoId": "gJh03s2HNeo",
    "level": "Beginner",
    "time": 5,
    "region": "Core",
    "complexity": "Easy",
    "instructions": [
      "Test_Exr","Test_Exr","Test_Exr"
    ],
    "shortThumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise.png",
    "exerciseId": 42,
    "description": "Test_Exr",
    "subcategory": "breathing"
  }
}
###

POST https://cloud.appwrite.io/v1/databases/66c3312f002e44e586ce/collections/66c76bdf0003e4f2041f/documents
Content-Type: application/json
X-Appwrite-Project: 66c32ed800357b5e7314
X-Appwrite-Key: 27fcf2ca888ed890e1dc68d5cf5f450d5ada0843c1ba560e450f37335c4b39de2b74ad7b44ede4a609e12495c90dc680903ebf3784b91f8943ada57b91996efa10cea61413f69fb3419633adbb17c70ca302103279a7b42e053beefdc693216f131cef6b910f24fb06542b8b09936f0d10997fd3f7f6f69f7cad9398e77366ad

{
  "databaseId": "66c3312f002e44e586ce",
  "collectionId": "66c76bdf0003e4f2041f",
  "documentId": "exercise-043",
  "data": {
    "title": "Rib Breathing with Resistance Band",
    "russianTitle": "Дыхание ребрами с резиной",
    "thumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise-big.png",
    "youtubeVideoId": "gJh03s2HNeo",
    "level": "Beginner",
    "time": 5,
    "region": "Core",
    "complexity": "Easy",
    "instructions": [
      "Test_Exr","Test_Exr","Test_Exr"
    ],
    "shortThumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise.png",
    "exerciseId": 43,
    "description": "Test_Exr",
    "subcategory": "breathing"
  }
}
###

POST https://cloud.appwrite.io/v1/databases/66c3312f002e44e586ce/collections/66c76bdf0003e4f2041f/documents
Content-Type: application/json
X-Appwrite-Project: 66c32ed800357b5e7314
X-Appwrite-Key: 27fcf2ca888ed890e1dc68d5cf5f450d5ada0843c1ba560e450f37335c4b39de2b74ad7b44ede4a609e12495c90dc680903ebf3784b91f8943ada57b91996efa10cea61413f69fb3419633adbb17c70ca302103279a7b42e053beefdc693216f131cef6b910f24fb06542b8b09936f0d10997fd3f7f6f69f7cad9398e77366ad

{
  "databaseId": "66c3312f002e44e586ce",
  "collectionId": "66c76bdf0003e4f2041f",
  "documentId": "exercise-044",
  "data": {
    "title": "Chest Breathing",
    "russianTitle": "Дыхание грудным",
    "thumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise-big.png",
    "youtubeVideoId": "gJh03s2HNeo",
    "level": "Beginner",
    "time": 5,
    "region": "Core",
    "complexity": "Easy",
    "instructions": [
      "Test_Exr","Test_Exr","Test_Exr"
    ],
    "shortThumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise.png",
    "exerciseId": 44,
    "description": "Test_Exr",
    "subcategory": "breathing"
  }
}
###

POST https://cloud.appwrite.io/v1/databases/66c3312f002e44e586ce/collections/66c76bdf0003e4f2041f/documents
Content-Type: application/json
X-Appwrite-Project: 66c32ed800357b5e7314
X-Appwrite-Key: 27fcf2ca888ed890e1dc68d5cf5f450d5ada0843c1ba560e450f37335c4b39de2b74ad7b44ede4a609e12495c90dc680903ebf3784b91f8943ada57b91996efa10cea61413f69fb3419633adbb17c70ca302103279a7b42e053beefdc693216f131cef6b910f24fb06542b8b09936f0d10997fd3f7f6f69f7cad9398e77366ad

{
  "databaseId": "66c3312f002e44e586ce",
  "collectionId": "66c76bdf0003e4f2041f",
  "documentId": "exercise-045",
  "data": {
    "title": "Alternate Breathing",
    "russianTitle": "Дыхание поочередно",
    "thumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise-big.png",
    "youtubeVideoId": "gJh03s2HNeo",
    "level": "Beginner",
    "time": 5,
    "region": "Core",
    "complexity": "Easy",
    "instructions": [
      "Test_Exr","Test_Exr","Test_Exr"
    ],
    "shortThumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise.png",
    "exerciseId": 45,
    "description": "Test_Exr",
    "subcategory": "breathing"
  }
}
###

POST https://cloud.appwrite.io/v1/databases/66c3312f002e44e586ce/collections/66c76bdf0003e4f2041f/documents
Content-Type: application/json
X-Appwrite-Project: 66c32ed800357b5e7314
X-Appwrite-Key: 27fcf2ca888ed890e1dc68d5cf5f450d5ada0843c1ba560e450f37335c4b39de2b74ad7b44ede4a609e12495c90dc680903ebf3784b91f8943ada57b91996efa10cea61413f69fb3419633adbb17c70ca302103279a7b42e053beefdc693216f131cef6b910f24fb06542b8b09936f0d10997fd3f7f6f69f7cad9398e77366ad

{
  "databaseId": "66c3312f002e44e586ce",
  "collectionId": "66c76bdf0003e4f2041f",
  "documentId": "exercise-046",
  "data": {
    "title": "Breathing with Pause",
    "russianTitle": "Дыхание с паузой",
    "thumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise-big.png",
    "youtubeVideoId": "gJh03s2HNeo",
    "level": "Beginner",
    "time": 5,
    "region": "Core",
    "complexity": "Easy",
    "instructions": [
      "Test_Exr","Test_Exr","Test_Exr"
    ],
    "shortThumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise.png",
    "exerciseId": 46,
    "description": "Test_Exr",
    "subcategory": "breathing"
  }
}
###

POST https://cloud.appwrite.io/v1/databases/66c3312f002e44e586ce/collections/66c76bdf0003e4f2041f/documents
Content-Type: application/json
X-Appwrite-Project: 66c32ed800357b5e7314
X-Appwrite-Key: 27fcf2ca888ed890e1dc68d5cf5f450d5ada0843c1ba560e450f37335c4b39de2b74ad7b44ede4a609e12495c90dc680903ebf3784b91f8943ada57b91996efa10cea61413f69fb3419633adbb17c70ca302103279a7b42e053beefdc693216f131cef6b910f24fb06542b8b09936f0d10997fd3f7f6f69f7cad9398e77366ad

{
  "databaseId": "66c3312f002e44e586ce",
  "collectionId": "66c76bdf0003e4f2041f",
  "documentId": "exercise-047",
  "data": {
    "title": "Posterior Rib Breathing",
    "russianTitle": "Дыхание задний отдел ребер",
    "thumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise-big.png",
    "youtubeVideoId": "gJh03s2HNeo",
    "level": "Beginner",
    "time": 5,
    "region": "Core",
    "complexity": "Easy",
    "instructions": [
      "Test_Exr","Test_Exr","Test_Exr"
    ],
    "shortThumbnail": "https://storage.googleapis.com/banner-ai-saved-images/exercise.png",
    "exerciseId": 47,
    "description": "Test_Exr",
    "subcategory": "breathing"
  }
}
